public class BuiltInExceptionsExample {
    public static void main(String[] args) {
        try {
           
            int a = 10;
            int b = 0;
            int c = a / b; 
        } catch (ArithmeticException e) {
            System.out.println("Caught an ArithmeticException: " + e.getMessage());
        }

        System.out.println("End of program");
    }
}
